server:
  port: 8080

eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-service
          uri: lb://payment-service:9091
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/(?<path>.*), /$\{path}
        - id: product-service
          uri: lb://product-service:9092
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<path>.*), /$\{path}
        - id: dealer-service
          uri: lb://dealer-service:9093
          predicates:
            - Path=/api/dealer/**
          filters:
            - RewritePath=/api/dealer/(?<path>.*), /$\{path}
        - id: inventory-service
          uri: lb://inventory-service:9094
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/inventory/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service:9095
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<path>.*), /$\{path}

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1